var setup = {

    "scenarioLines": 12,
    "scenarioCollums": 12,
    "scenarioBlockWidth": 26,
    "scenarioBlockHeight": 28,
    "scenarioId": "td",
    "coderSpaceId": "coderSpaceTable",
    "coderPosition": "coderSpaceTable" + "Cell0_1",
    "numOfFunctions": 5,
    "functionLength": 8,
    "functionsWidth": 40,
    "functionsHeigth": 40,
    "speed": 1500,
    "runnerPosition": [1, 2],
    "runnerPosition0": [1, 2],
    "runerDirection": 20003, //gambi das brabas
    "runnerImageUrl": "url('./assets/pac-manaD.png')",
    "moveCode": 1,
    "rotateClockCode": 2,
    "rotateCounterClockCode": 3,
    "f1Code": 4,
    "f2Code": 5,
    "f3Code": 6,
    "f4Code": 7,
    "f5Code": 8,
    "level": [["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "r", "g", "b", "h", "h", "b", "b", "b", "b", "b", "h"],
    ["h", "r", "g", "b", "h", "h", "b", "r", "r", "r", "b", "h"],
    ["h", "r", "g", "b", "b", "b", "b", "r", "g", "r", "b", "h"],
    ["h", "r", "g", "g", "g", "b", "h", "h", "h", "r", "b", "h"],
    ["h", "r", "r", "r", "g", "b", "h", "h", "h", "r", "b", "h"],
    ["h", "h", "h", "r", "g", "b", "h", "h", "r", "r", "b", "h"],
    ["h", "h", "h", "r", "g", "b", "h", "r", "r", "b", "b", "h"],
    ["h", "h", "h", "r", "g", "b", "b", "r", "b", "r", "r", "h"],
    ["h", "h", "h", "r", "r", "g", "g", "b", "b", "b", "b", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"]
    ],
    "stars": [["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "*", "_", "_", "_", "_", "*", "*", "*", "_", "_"],
    ["_", "_", "*", "_", "_", "_", "_", "*", "_", "*", "_", "_"],
    ["_", "_", "*", "*", "*", "_", "_", "_", "_", "*", "_", "_"],
    ["_", "_", "_", "_", "*", "_", "_", "_", "-", "*", "-", "_"],
    ["_", "_", "_", "_", "*", "_", "_", "_", "*", "*", "_", "_"],
    ["_", "_", "_", "_", "*", "_", "_", "*", "*", "_", "_", "_"],
    ["_", "_", "_", "_", "*", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    "starImageUrl": "url('./assets/star.png')",
    "starCount": 100,
    "manaCount": 100
}