var level1 = {

    "scenarioLines": 12,
    "scenarioCollums": 12,
    "scenarioBlockWidth": 26,
    "scenarioBlockHeight": 28,
    "scenarioId": "td",
    "coderSpaceId": "coderSpaceTable",
    "coderPosition": "coderSpaceTable" + "Cell0_1",
    "numOfFunctions": 5,
    "functionLength": 8,
    "functionsWidth": 40,
    "functionsHeigth": 40,
    "speed": 1500,
    "runnerPosition": [5, 6],
    "runnerPosition0": [5, 6],
    "runerDirection": 20002, //gambi das brabas
    "runerDirection0": 20002, //gambi das brabas lvls 2
    "runnerImageUrl": "url('./assets/pac-manaF.png')",
    "runnerImageUrl0": "url('./assets/pac-manaF.png')",
    "moveCode": 1,
    "rotateClockCode": 2,
    "rotateCounterClockCode": 3,
    "f1Code": 4,
    "f2Code": 5,
    "f3Code": 6,
    "f4Code": 7,
    "f5Code": 8,
    "level": [["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "b", "b", "b", "b", "h", "h", "h", "h"],
    ["h", "h", "h", "b", "b", "b", "b", "b", "b", "h", "h", "h"],
    ["h", "h", "b", "b", "b", "b", "b", "b", "b", "b", "h", "h"],
    ["h", "h", "h", "b", "b", "b", "b", "b", "b", "h", "h", "h"],
    ["h", "h", "h", "h", "b", "b", "b", "b", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"]
    ],
    "stars": [["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "*", "_", "_", "_", "_", "_", "_", "*", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    "starImageUrl": "url('./assets/star.png')",
    "starCount": 2,
    "starCount0": 2,
    "manaCount": 100,
    "isLive": true
}

var level2 = {

    "scenarioLines": 12,
    "scenarioCollums": 12,
    "scenarioBlockWidth": 26,
    "scenarioBlockHeight": 28,
    "scenarioId": "td",
    "coderSpaceId": "coderSpaceTable",
    "coderPosition": "coderSpaceTable" + "Cell0_1",
    "numOfFunctions": 5,
    "functionLength": 8,
    "functionsWidth": 40,
    "functionsHeigth": 40,
    "speed": 1500,
    "runnerPosition": [5, 1],
    "runnerPosition0": [5, 1],
    "runerDirection": 20002, //gambi das brabas
    "runerDirection0": 20002, //gambi das brabas lvls 2
    "runnerImageUrl": "url('./assets/pac-manaF.png')",
    "runnerImageUrl0": "url('./assets/pac-manaF.png')",
    "moveCode": 1,
    "rotateClockCode": 2,
    "rotateCounterClockCode": 3,
    "f1Code": 4,
    "f2Code": 5,
    "f3Code": 6,
    "f4Code": 7,
    "f5Code": 8,
    "level": [["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "b", "b", "b", "b", "b", "b", "b", "b", "b", "b", "h"],
    ["h", "b", "b", "b", "b", "b", "b", "b", "b", "b", "b", "h"],
    ["h", "b", "b", "b", "b", "b", "b", "b", "b", "b", "b", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"]
    ],
    "stars": [["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "*", "*", "*", "*", "*", "*", "*", "*", "*", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    "starImageUrl": "url('./assets/star.png')",
    "starCount": 9,
    "starCount0": 9,
    "manaCount": 100
}

var level3 = {

    "scenarioLines": 12,
    "scenarioCollums": 12,
    "scenarioBlockWidth": 26,
    "scenarioBlockHeight": 28,
    "scenarioId": "td",
    "coderSpaceId": "coderSpaceTable",
    "coderPosition": "coderSpaceTable" + "Cell0_1",
    "numOfFunctions": 5,
    "functionLength": 8,
    "functionsWidth": 40,
    "functionsHeigth": 40,
    "speed": 1500,
    "runnerPosition": [5, 4],
    "runnerPosition0": [5, 4],
    "runerDirection": 20002, //gambi das brabas
    "runerDirection0": 20002, //gambi das brabas lvls 2
    "runnerImageUrl": "url('./assets/pac-manaF.png')",
    "runnerImageUrl0": "url('./assets/pac-manaF.png')",
    "moveCode": 1,
    "rotateClockCode": 2,
    "rotateCounterClockCode": 3,
    "f1Code": 4,
    "f2Code": 5,
    "f3Code": 6,
    "f4Code": 7,
    "f5Code": 8,
    "level": [["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "b", "b", "b", "b", "h", "h", "h", "h"],
    ["h", "h", "h", "b", "b", "b", "b", "b", "b", "h", "h", "h"],
    ["h", "h", "b", "b", "b", "b", "b", "b", "b", "b", "h", "h"],
    ["h", "h", "h", "b", "b", "b", "b", "b", "b", "h", "h", "h"],
    ["h", "h", "h", "h", "b", "b", "b", "b", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"]
    ],
    "stars": [["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "*", "_", "_", "_", "_", "_", "_", "*", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    "starImageUrl": "url('./assets/star.png')",
    "starCount": 2,
    "starCount0": 2,
    "manaCount": 100
}


var level4 = {

    "scenarioLines": 12,
    "scenarioCollums": 12,
    "scenarioBlockWidth": 26,
    "scenarioBlockHeight": 28,
    "scenarioId": "td",
    "coderSpaceId": "coderSpaceTable",
    "coderPosition": "coderSpaceTable" + "Cell0_1",
    "numOfFunctions": 5,
    "functionLength": 8,
    "functionsWidth": 40,
    "functionsHeigth": 40,
    "speed": 1500,
    "runnerPosition": [2, 2],
    "runnerPosition0": [2, 2],
    "runerDirection": 20002, //gambi das brabas
    "runerDirection0": 20002, //gambi das brabas lvls 2
    "runnerImageUrl": "url('./assets/pac-manaF.png')",
    "runnerImageUrl0": "url('./assets/pac-manaF.png')",
    "moveCode": 1,
    "rotateClockCode": 2,
    "rotateCounterClockCode": 3,
    "f1Code": 4,
    "f2Code": 5,
    "f3Code": 6,
    "f4Code": 7,
    "f5Code": 8,
    "level": [["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "r", "r", "r", "r", "r", "r", "r", "b", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "r", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "r", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "r", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "r", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "r", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "r", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "r", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"]
    ],
    "stars": [["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "*", "*", "*", "*", "*", "*", "*", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "*", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "*", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "*", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "*", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "*", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "*", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "*", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    "starImageUrl": "url('./assets/star.png')",
    "starCount": 14,
    "starCount0": 14,
    "manaCount": 100
}

var level5 = {

    "scenarioLines": 12,
    "scenarioCollums": 12,
    "scenarioBlockWidth": 26,
    "scenarioBlockHeight": 28,
    "scenarioId": "td",
    "coderSpaceId": "coderSpaceTable",
    "coderPosition": "coderSpaceTable" + "Cell0_1",
    "numOfFunctions": 5,
    "functionLength": 8,
    "functionsWidth": 40,
    "functionsHeigth": 40,
    "speed": 1500,
    "runnerPosition": [4, 7],
    "runnerPosition0": [4, 7],
    "runerDirection": 20002, //gambi das brabas
    "runerDirection0": 20002, //gambi das brabas lvls 2
    "runnerImageUrl": "url('./assets/pac-manaF.png')",
    "runnerImageUrl0": "url('./assets/pac-manaF.png')",
    "moveCode": 1,
    "rotateClockCode": 2,
    "rotateCounterClockCode": 3,
    "f1Code": 4,
    "f2Code": 5,
    "f3Code": 6,
    "f4Code": 7,
    "f5Code": 8,
    "level": [["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "b", "b", "b", "b", "b", "b", "b", "b", "b", "r", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"]
    ],
    "stars": [["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "*", "*", "*", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    "starImageUrl": "url('./assets/star.png')",
    "starCount": 3,
    "starCount0": 3,
    "manaCount": 100
}

var level6 = {

    "scenarioLines": 12,
    "scenarioCollums": 12,
    "scenarioBlockWidth": 26,
    "scenarioBlockHeight": 28,
    "scenarioId": "td",
    "coderSpaceId": "coderSpaceTable",
    "coderPosition": "coderSpaceTable" + "Cell0_1",
    "numOfFunctions": 5,
    "functionLength": 8,
    "functionsWidth": 40,
    "functionsHeigth": 40,
    "speed": 1500,
    "runnerPosition": [1, 4],
    "runnerPosition0": [1, 4],
    "runerDirection": 20002, //gambi das brabas
    "runerDirection0": 20002, //gambi das brabas lvls 2
    "runnerImageUrl": "url('./assets/pac-manaF.png')",
    "runnerImageUrl0": "url('./assets/pac-manaF.png')",
    "moveCode": 1,
    "rotateClockCode": 2,
    "rotateCounterClockCode": 3,
    "f1Code": 4,
    "f2Code": 5,
    "f3Code": 6,
    "f4Code": 7,
    "f5Code": 8,
    "level": [["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "r", "b", "b", "b", "b", "g", "h", "h", "h"],
    ["h", "h", "h", "r", "b", "b", "b", "b", "g", "h", "h", "h"],
    ["h", "h", "h", "r", "b", "b", "b", "b", "g", "h", "h", "h"],
    ["h", "h", "h", "r", "b", "b", "b", "b", "g", "h", "h", "h"],
    ["h", "h", "h", "r", "b", "b", "b", "b", "g", "h", "h", "h"],
    ["h", "h", "h", "r", "b", "b", "b", "b", "g", "h", "h", "h"],
    ["h", "h", "h", "r", "b", "b", "b", "b", "g", "h", "h", "h"],
    ["h", "h", "h", "r", "b", "b", "b", "b", "g", "h", "h"],
    ["h", "h", "h", "r", "b", "b", "b", "b", "g", "h", "h", "h"],
    ["h", "h", "h", "r", "b", "b", "b", "b", "g", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"]
    ],
    "stars": [["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "*", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "*", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "*", "_", "*", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "*", "_", "*", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "*", "_", "*", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "*", "_", "*", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "*", "_", "*", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "*", "_", "*", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "*", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "*", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    "starImageUrl": "url('./assets/star.png')",
    "starCount": 1,
    "manaCount": 100
}

var level7 = {

    "scenarioLines": 12,
    "scenarioCollums": 12,
    "scenarioBlockWidth": 26,
    "scenarioBlockHeight": 28,
    "scenarioId": "td",
    "coderSpaceId": "coderSpaceTable",
    "coderPosition": "coderSpaceTable" + "Cell0_1",
    "numOfFunctions": 5,
    "functionLength": 8,
    "functionsWidth": 40,
    "functionsHeigth": 40,
    "speed": 1500,
    "runnerPosition": [6, 6],
    "runnerPosition0": [6, 6],
    "runerDirection": 20002, //gambi das brabas
    "runerDirection0": 20002, //gambi das brabas lvls 2
    "runnerImageUrl": "url('./assets/pac-manaF.png')",
    "runnerImageUrl0": "url('./assets/pac-manaF.png')",
    "moveCode": 1,
    "rotateClockCode": 2,
    "rotateCounterClockCode": 3,
    "f1Code": 4,
    "f2Code": 5,
    "f3Code": 6,
    "f4Code": 7,
    "f5Code": 8,
    "level": [["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "b", "b", "g", "b", "g", "b", "b", "h", "h", "h"],
    ["h", "h", "b", "h", "h", "h", "h", "h", "b", "h", "h", "h"],
    ["h", "h", "b", "b", "b", "h", "b", "b", "b", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"]
    ],
    "stars": [["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "*", "_", "_", "*", "_", "_", "*", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "*", "_", "*", "_", "_", "_", "*", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    "starImageUrl": "url('./assets/star.png')",
    "starCount": 1,
    "manaCount": 100
}

var level8 = {

    "scenarioLines": 12,
    "scenarioCollums": 12,
    "scenarioBlockWidth": 26,
    "scenarioBlockHeight": 28,
    "scenarioId": "td",
    "coderSpaceId": "coderSpaceTable",
    "coderPosition": "coderSpaceTable" + "Cell0_1",
    "numOfFunctions": 5,
    "functionLength": 8,
    "functionsWidth": 40,
    "functionsHeigth": 40,
    "speed": 1500,
    "runnerPosition": [7, 6],
    "runnerPosition0": [7, 6],
    "runerDirection": 20002, //gambi das brabas
    "runerDirection0": 20002, //gambi das brabas lvls 2
    "runnerImageUrl": "url('./assets/pac-manaF.png')",
    "runnerImageUrl0": "url('./assets/pac-manaF.png')",
    "moveCode": 1,
    "rotateClockCode": 2,
    "rotateCounterClockCode": 3,
    "f1Code": 4,
    "f2Code": 5,
    "f3Code": 6,
    "f4Code": 7,
    "f5Code": 8,
    "level": [["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "h"],
    ["h", "r", "b", "b", "b", "b", "b", "r", "r", "b", "r", "h"],
    ["h", "r", "b", "b", "b", "b", "r", "r", "b", "b", "r", "h"],
    ["h", "r", "b", "b", "b", "r", "g", "b", "b", "b", "r", "h"],
    ["h", "r", "b", "b", "r", "r", "b", "b", "b", "b", "r", "h"],
    ["h", "r", "b", "r", "r", "b", "b", "b", "b", "b", "r", "h"],
    ["h", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"]
    ],
    "stars": [["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "*", "*", "*", "*", "*", "*", "*", "*", "*", "*", "_"],
    ["_", "*", "*", "*", "*", "*", "*", "*", "*", "*", "*", "_"],
    ["_", "*", "*", "*", "*", "*", "*", "*", "*", "*", "*", "_"],
    ["_", "*", "*", "*", "*", "*", "_", "*", "*", "*", "*", "_"],
    ["_", "*", "*", "*", "*", "*", "*", "*", "*", "*", "*", "_"],
    ["_", "*", "*", "*", "*", "*", "*", "*", "*", "*", "*", "_"],
    ["_", "*", "*", "*", "*", "*", "*", "*", "*", "*", "*", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    "starImageUrl": "url('./assets/star.png')",
    "starCount": 1,
    "manaCount": 100
}

var level9 = {

    "scenarioLines": 12,
    "scenarioCollums": 12,
    "scenarioBlockWidth": 26,
    "scenarioBlockHeight": 28,
    "scenarioId": "td",
    "coderSpaceId": "coderSpaceTable",
    "coderPosition": "coderSpaceTable" + "Cell0_1",
    "numOfFunctions": 5,
    "functionLength": 8,
    "functionsWidth": 40,
    "functionsHeigth": 40,
    "speed": 1500,
    "runnerPosition": [5, 5],
    "runnerPosition0": [5, 5],
    "runerDirection": 20002, //gambi das brabas
    "runerDirection0": 20002, //gambi das brabas lvls 2
    "runnerImageUrl": "url('./assets/pac-manaF.png')",
    "runnerImageUrl0": "url('./assets/pac-manaF.png')",
    "moveCode": 1,
    "rotateClockCode": 2,
    "rotateCounterClockCode": 3,
    "f1Code": 4,
    "f2Code": 5,
    "f3Code": 6,
    "f4Code": 7,
    "f5Code": 8,
    "level": [["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "b", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "g", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "b", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "b", "h", "h", "h", "h", "h", "h"],
    ["h", "b", "g", "b", "b", "r", "b", "b", "g", "b", "h", "h"],
    ["h", "h", "h", "h", "h", "b", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "b", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "g", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "b", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"]
    ],
    "stars": [["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "*", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "*", "_", "_", "_", "_", "_", "_", "_", "*", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "*", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    "starImageUrl": "url('./assets/star.png')",
    "starCount": 1,
    "manaCount": 100
}

var level10 = {

    "scenarioLines": 12,
    "scenarioCollums": 12,
    "scenarioBlockWidth": 26,
    "scenarioBlockHeight": 28,
    "scenarioId": "td",
    "coderSpaceId": "coderSpaceTable",
    "coderPosition": "coderSpaceTable" + "Cell0_1",
    "numOfFunctions": 5,
    "functionLength": 8,
    "functionsWidth": 40,
    "functionsHeigth": 40,
    "speed": 1500,
    "runnerPosition": [5, 6],
    "runnerPosition0": [5, 6],
    "runerDirection": 20002, //gambi das brabas
    "runerDirection0": 20002, //gambi das brabas lvls 2
    "runnerImageUrl": "url('./assets/pac-manaF.png')",
    "runnerImageUrl0": "url('./assets/pac-manaF.png')",
    "moveCode": 1,
    "rotateClockCode": 2,
    "rotateCounterClockCode": 3,
    "f1Code": 4,
    "f2Code": 5,
    "f3Code": 6,
    "f4Code": 7,
    "f5Code": 8,
    "level": [["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "r", "r", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "g", "b", "b", "r", "b", "r", "b", "g", "b", "h"],
    ["h", "h", "b", "g", "h", "b", "b", "b", "g", "b", "b", "h"],
    ["h", "h", "r", "b", "h", "g", "b", "g", "b", "r", "r", "h"],
    ["h", "h", "b", "r", "h", "b", "h", "h", "g", "b", "b", "h"],
    ["h", "h", "r", "b", "h", "b", "g", "b", "b", "b", "r", "h"],
    ["h", "h", "b", "r", "h", "h", "h", "h", "h", "g", "b", "h"],
    ["h", "h", "r", "b", "g", "b", "r", "b", "r", "b", "g", "h"],
    ["h", "h", "b", "g", "b", "r", "b", "r", "b", "r", "b", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"]
    ],
    "stars": [["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "*", "*", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "*", "_", "_", "*", "_", "*", "_", "*", "_", "_"],
    ["_", "_", "_", "*", "_", "_", "_", "_", "*", "_", "_", "_"],
    ["_", "_", "*", "_", "_", "*", "_", "*", "_", "*", "*", "_"],
    ["_", "_", "_", "*", "_", "_", "_", "_", "*", "_", "_", "_"],
    ["_", "_", "*", "_", "_", "_", "*", "_", "_", "_", "*", "_"],
    ["_", "_", "_", "*", "_", "_", "_", "_", "_", "*", "_", "_"],
    ["_", "_", "*", "_", "*", "_", "*", "_", "*", "_", "*", "_"],
    ["_", "_", "_", "*", "_", "*", "_", "*", "_", "*", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    "starImageUrl": "url('./assets/star.png')",
    "starCount": 1,
    "manaCount": 100
}

var level11 = {

    "scenarioLines": 12,
    "scenarioCollums": 12,
    "scenarioBlockWidth": 26,
    "scenarioBlockHeight": 28,
    "scenarioId": "td",
    "coderSpaceId": "coderSpaceTable",
    "coderPosition": "coderSpaceTable" + "Cell0_1",
    "numOfFunctions": 5,
    "functionLength": 8,
    "functionsWidth": 40,
    "functionsHeigth": 40,
    "speed": 1500,
    "runnerPosition": [6, 5],
    "runnerPosition0": [6, 5],
    "runerDirection": 20002, //gambi das brabas
    "runerDirection0": 20002, //gambi das brabas lvls 2
    "runnerImageUrl": "url('./assets/pac-manaF.png')",
    "runnerImageUrl0": "url('./assets/pac-manaF.png')",
    "moveCode": 1,
    "rotateClockCode": 2,
    "rotateCounterClockCode": 3,
    "f1Code": 4,
    "f2Code": 5,
    "f3Code": 6,
    "f4Code": 7,
    "f5Code": 8,
    "level": [["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "b", "b", "b", "b", "b", "b", "b", "b", "b", "h", "h"],
    ["h", "b", "h", "b", "h", "b", "h", "b", "h", "b", "h", "h"],
    ["h", "b", "b", "r", "b", "b", "b", "r", "b", "b", "h", "h"],
    ["h", "b", "h", "b", "h", "b", "h", "b", "h", "b", "h", "h"],
    ["h", "b", "b", "b", "b", "g", "b", "b", "b", "b", "h", "h"],
    ["h", "b", "h", "b", "h", "b", "h", "b", "h", "b", "h", "h"],
    ["h", "b", "b", "r", "b", "b", "b", "r", "b", "b", "h", "h"],
    ["h", "b", "h", "b", "h", "b", "h", "b", "h", "b", "h", "h"],
    ["h", "b", "b", "b", "b", "b", "b", "b", "b", "b", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"]
    ],
    "stars": [["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "*", "*", "*", "*", "*", "*", "*", "*", "*", "_", "_"],
    ["_", "*", "_", "*", "_", "*", "_", "*", "_", "*", "_", "_"],
    ["_", "*", "*", "*", "*", "*", "*", "*", "*", "*", "_", "_"],
    ["_", "*", "_", "*", "_", "*", "_", "*", "_", "*", "_", "_"],
    ["_", "*", "*", "*", "*", "_", "*", "*", "*", "*", "_", "_"],
    ["_", "*", "_", "*", "_", "*", "_", "*", "_", "*", "_", "_"],
    ["_", "*", "*", "*", "*", "*", "*", "*", "*", "*", "_", "_"],
    ["_", "*", "_", "*", "_", "*", "_", "*", "_", "*", "_", "_"],
    ["_", "*", "*", "*", "*", "*", "*", "*", "*", "*", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    "starImageUrl": "url('./assets/star.png')",
    "starCount": 1,
    "manaCount": 100
}

var level12 = {

    "scenarioLines": 12,
    "scenarioCollums": 12,
    "scenarioBlockWidth": 26,
    "scenarioBlockHeight": 28,
    "scenarioId": "td",
    "coderSpaceId": "coderSpaceTable",
    "coderPosition": "coderSpaceTable" + "Cell0_1",
    "numOfFunctions": 5,
    "functionLength": 8,
    "functionsWidth": 40,
    "functionsHeigth": 40,
    "speed": 1500,
    "runnerPosition": [6, 5],
    "runnerPosition0": [6, 5],
    "runerDirection": 20002, //gambi das brabas
    "runerDirection0": 20002, //gambi das brabas lvls 2
    "runnerImageUrl": "url('./assets/pac-manaF.png')",
    "runnerImageUrl0": "url('./assets/pac-manaF.png')",
    "moveCode": 1,
    "rotateClockCode": 2,
    "rotateCounterClockCode": 3,
    "f1Code": 4,
    "f2Code": 5,
    "f3Code": 6,
    "f4Code": 7,
    "f5Code": 8,
    "level": [["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "b", "b", "b", "b", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "b", "h", "h", "b", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "b", "h", "g", "b", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "b", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "b", "b", "b", "b", "b", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"]
    ],
    "stars": [["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "*", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    "starImageUrl": "url('./assets/star.png')",
    "starCount": 1,
    "manaCount": 100
}

var level13 = {

    "scenarioLines": 12,
    "scenarioCollums": 12,
    "scenarioBlockWidth": 26,
    "scenarioBlockHeight": 28,
    "scenarioId": "td",
    "coderSpaceId": "coderSpaceTable",
    "coderPosition": "coderSpaceTable" + "Cell0_1",
    "numOfFunctions": 5,
    "functionLength": 8,
    "functionsWidth": 40,
    "functionsHeigth": 40,
    "speed": 1500,
    "runnerPosition": [4, 1],
    "runnerPosition0": [4, 1],
    "runerDirection": 20002, //gambi das brabas
    "runerDirection0": 20002, //gambi das brabas lvls 2
    "runnerImageUrl": "url('./assets/pac-manaF.png')",
    "runnerImageUrl0": "url('./assets/pac-manaF.png')",
    "moveCode": 1,
    "rotateClockCode": 2,
    "rotateCounterClockCode": 3,
    "f1Code": 4,
    "f2Code": 5,
    "f3Code": 6,
    "f4Code": 7,
    "f5Code": 8,
    "level": [["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "b", "b", "b", "b", "b", "b", "b", "r", "b", "b", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "b", "h", "b", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "b", "b", "b", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"]
    ],
    "stars": [["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "*", "*", "*", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "*", "_", "*", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "*", "*", "*", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    "starImageUrl": "url('./assets/star.png')",
    "starCount": 1,
    "manaCount": 100
}

var level14 = {

    "scenarioLines": 12,
    "scenarioCollums": 12,
    "scenarioBlockWidth": 26,
    "scenarioBlockHeight": 28,
    "scenarioId": "td",
    "coderSpaceId": "coderSpaceTable",
    "coderPosition": "coderSpaceTable" + "Cell0_1",
    "numOfFunctions": 5,
    "functionLength": 8,
    "functionsWidth": 40,
    "functionsHeigth": 40,
    "speed": 1500,
    "runnerPosition": [10, 1],
    "runnerPosition0": [10, 1],
    "runerDirection": 20002, //gambi das brabas
    "runerDirection0": 20002, //gambi das brabas lvls 2
    "runnerImageUrl": "url('./assets/pac-manaF.png')",
    "runnerImageUrl0": "url('./assets/pac-manaF.png')",
    "moveCode": 1,
    "rotateClockCode": 2,
    "rotateCounterClockCode": 3,
    "f1Code": 4,
    "f2Code": 5,
    "f3Code": 6,
    "f4Code": 7,
    "f5Code": 8,
    "level": [["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "r", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "b", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "b", "h", "r", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "b", "h", "b", "h", "h", "h", "h", "h", "h", "r", "h"],
    ["h", "b", "r", "b", "h", "r", "h", "h", "h", "h", "b", "h"],
    ["h", "b", "b", "b", "h", "b", "r", "h", "h", "h", "b", "h"],
    ["h", "b", "b", "b", "h", "b", "b", "h", "h", "r", "b", "h"],
    ["h", "b", "b", "b", "h", "b", "b", "h", "h", "b", "b", "h"],
    ["h", "b", "b", "b", "r", "b", "b", "r", "r", "b", "b", "h"],
    ["h", "b", "b", "b", "b", "b", "b", "b", "b", "b", "b", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"]
    ],
    "stars": [["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "*", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "*", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "-", "*", "_"],
    ["_", "_", "*", "_", "_", "*", "_", "_", "-", "_", "-", "_"],
    ["_", "_", "_", "_", "_", "_", "*", "_", "-", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "*", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "*", "_", "_", "*", "*", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    "starImageUrl": "url('./assets/star.png')",
    "starCount": 1,
    "manaCount": 100
}

var level15 = {

    "scenarioLines": 12,
    "scenarioCollums": 12,
    "scenarioBlockWidth": 26,
    "scenarioBlockHeight": 28,
    "scenarioId": "td",
    "coderSpaceId": "coderSpaceTable",
    "coderPosition": "coderSpaceTable" + "Cell0_1",
    "numOfFunctions": 5,
    "functionLength": 8,
    "functionsWidth": 40,
    "functionsHeigth": 40,
    "speed": 1500,
    "runnerPosition": [1, 2],
    "runnerPosition0": [1, 2],
    "runerDirection": 20003, //gambi das brabas
    "runerDirection0": 20002, //gambi das brabas lvls 2
    "runnerImageUrl": "url('./assets/pac-manaD.png')",
    "runnerImageUrl0": "url('./assets/pac-manaD.png')",
    "moveCode": 1,
    "rotateClockCode": 2,
    "rotateCounterClockCode": 3,
    "f1Code": 4,
    "f2Code": 5,
    "f3Code": 6,
    "f4Code": 7,
    "f5Code": 8,
    "level": [["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "r", "g", "b", "h", "h", "b", "b", "b", "b", "b", "h"],
    ["h", "r", "g", "b", "h", "h", "b", "r", "r", "r", "b", "h"],
    ["h", "r", "g", "b", "b", "b", "b", "r", "g", "r", "b", "h"],
    ["h", "r", "g", "g", "g", "b", "h", "h", "h", "r", "b", "h"],
    ["h", "r", "r", "r", "g", "b", "h", "h", "h", "r", "b", "h"],
    ["h", "h", "h", "r", "g", "b", "h", "h", "r", "r", "b", "h"],
    ["h", "h", "h", "r", "g", "b", "h", "r", "r", "b", "b", "h"],
    ["h", "h", "h", "r", "g", "b", "b", "r", "b", "r", "r", "h"],
    ["h", "h", "h", "r", "r", "g", "g", "b", "b", "b", "b", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"],
    ["h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h"]
    ],
    "stars": [["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "*", "_", "_", "_", "_", "*", "*", "*", "_", "_"],
    ["_", "_", "*", "_", "_", "_", "_", "*", "_", "*", "_", "_"],
    ["_", "_", "*", "*", "*", "_", "_", "_", "_", "*", "_", "_"],
    ["_", "_", "_", "_", "*", "_", "_", "_", "-", "*", "-", "_"],
    ["_", "_", "_", "_", "*", "_", "_", "_", "*", "*", "_", "_"],
    ["_", "_", "_", "_", "*", "_", "_", "*", "*", "_", "_", "_"],
    ["_", "_", "_", "_", "*", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
    "starImageUrl": "url('./assets/star.png')",
    "starCount": 100,
    "manaCount": 100
}

var setup = level1;

var lvls = [
    level1,
    level2,
    level3,
    level4,
    level5,
    level6,
    level7,
    level8,
    level9,
    level10,
    level11,
    level12,
    level13,
    level14,
    level15
];